# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"@\n\x0fResponseMessage\x12\x0e\n\x06result\x18\x01 \x01(\x02\x12\x0c\n\x04zero\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1d\n\x05Input\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\x32\x9d\x01\n\nCalculator\x12\x1f\n\x03\x41\x64\x64\x12\x06.Input\x1a\x10.ResponseMessage\x12$\n\x08Subtract\x12\x06.Input\x1a\x10.ResponseMessage\x12$\n\x08Multiply\x12\x06.Input\x1a\x10.ResponseMessage\x12\"\n\x06\x44ivide\x12\x06.Input\x1a\x10.ResponseMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSEMESSAGE._serialized_start=20
  _RESPONSEMESSAGE._serialized_end=84
  _INPUT._serialized_start=86
  _INPUT._serialized_end=115
  _CALCULATOR._serialized_start=118
  _CALCULATOR._serialized_end=275
# @@protoc_insertion_point(module_scope)
